apiVersion: v1alpha1
kind: Setting
metadata:
  name: alipay-payment-settings
spec:
  forms:
    - group: alipay
      label: 支付宝设置
      formSchema:
        - $formkit: text
          label: 网关地址
          name: serverUrl
          help: "线上：https://openapi.alipay.com/gateway.do 沙箱：https://openapi.alipaydev.com/gateway.do"
        - $formkit: text
          label: AppId
          name: appId
          help: "开放平台上创建的应用的ID"
        - $formkit: text
          label: 应用私钥
          name: privateKey
          help: "应用私钥"
        - $formkit: text
          label: 应用公钥
          name: publicKey
          help: "应用公钥"
          