apiVersion: v1alpha1
kind: Setting
metadata:
  name: payment-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          label: IP黑名单
          name: blackListIp
          value: "127.0.0.1"
          help: "多个IP使用,分割"
        - $formkit: text
          label: 异步通知Token
          name: token
          value: "XZ0JV7t3IFNG7BLKOzJdwEFZOU42Ap5V"
          help: "回调通知会校验此Token是否一致, 建议使用随机的UUID去除-后的值"

