apiVersion: v1alpha1
kind: Setting
metadata:
  name: payment-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: checkbox
          help: "tmp checkbox"
          label: Tmp
          name: enable
          value: true
    - group: wechat
      label: 微信支付设置
      formSchema:
        - $formkit: text
          label: AppId
          name: AppId
        - $formkit: text
          label: 商户号
          name: merchantId
        - $formkit: text
          label: 商户API私钥
          name: privateKey
          help: "默认使用 RSA 字符串。如果以 file:// 开头则匹配路径，如：file:///opt/cert/apiclient_key.pem"
        - $formkit: text
          label: 商户证书序列号
          name: merchantSerialNumber
        - $formkit: text
          label: 商户APIV3密钥
          name: apiV3key